/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualanmobil;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.table.*;

/**
 *
 * @author USER
 */
public class FormMobil extends javax.swing.JFrame {
    Mobil mob = new Mobil();
    private TableColumn column;

    /**
     * Creates new form FormMobil
     */
    public FormMobil() {
        initComponents();
        mob.AksesData();
        isiTabel();
    }
    
    public void isiTabel() {
        DefaultTableModel tm = new DefaultTableModel();
        
        tm.addColumn("ID Mobil");
        tm.addColumn("Nama Mobil");
        
        try {
            mob.AksesData();
            mob.TampilData();
            Statement stat = mob.conn.createStatement();
            ResultSet res = stat.executeQuery(mob.sql);
            while(res.next()) {
                tm.addRow(new Object[] {res.getString(1), res.getString(2)});
            }tbMobil.setModel(tm);
        } catch (Exception e) {
        }
    }
    
    public void Bersih(){
        txtIdMobil.setText("");
        txtNamaMobil.setText("");
        txtIdMobil.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdMobil = new javax.swing.JTextField();
        txtNamaMobil = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMobil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("FORM MOBIL");

        jLabel2.setText("ID Mobil         :");

        jLabel3.setText("Nama Mobil  :");

        txtIdMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdMobilMousePressed(evt);
            }
        });
        txtIdMobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdMobilKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdMobilKeyTyped(evt);
            }
        });

        txtNamaMobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaMobilKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaMobilKeyTyped(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        tbMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Mobil", "Nama Mobil"
            }
        ));
        tbMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMobilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMobil);
        if (tbMobil.getColumnModel().getColumnCount() > 0) {
            tbMobil.getColumnModel().getColumn(0).setResizable(false);
            tbMobil.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btnSimpan))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdMobil)
                            .addComponent(txtNamaMobil)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(29, 29, 29)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(btnKeluar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtIdMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (txtIdMobil.getText().equals("") || txtNamaMobil.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Informasi Mobil");
        } else {
            try {
                mob.AksesData();
                mob.id_mobil = txtIdMobil.getText();
                mob.nama_mobil = txtNamaMobil.getText();
                mob.Edit();
                mob.res.executeUpdate(mob.sql);
                mob.conn.close();
                Bersih();
                isiTabel();
                
                JOptionPane.showMessageDialog(null, "Informasi Berhasil diUpdate");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menyimpan");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            mob.AksesData();
            mob.id_mobil = txtIdMobil.getText();
            mob.Hapus();
            mob.res.executeUpdate(mob.sql);
            mob.conn.close();
            isiTabel();
            Bersih();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMobilMouseClicked
        // TODO add your handling code here:
        int baris = tbMobil.getSelectedRow();
        String kolom1 = tbMobil.getValueAt(baris, 0).toString();
        String kolom2 = tbMobil.getValueAt(baris, 1).toString();
        
        txtIdMobil.setText(kolom1);
        txtNamaMobil.setText(kolom2); 
    }//GEN-LAST:event_tbMobilMouseClicked

    private void txtIdMobilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMobilMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMobilMousePressed

    private void txtIdMobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMobilKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtIdMobil.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan ID Mobil", "informasi", JOptionPane.INFORMATION_MESSAGE);
                txtIdMobil.requestFocus();
            } else {
                txtIdMobil.requestFocus();
            }
        }
    }//GEN-LAST:event_txtIdMobilKeyPressed

    private void txtIdMobilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMobilKeyTyped
        // TODO add your handling code here:
        if (txtIdMobil.getText().length()>4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdMobilKeyTyped

    private void txtNamaMobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaMobilKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtNamaMobil.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan Nama Mobil", "informasi", JOptionPane.INFORMATION_MESSAGE);
                txtNamaMobil.requestFocus();
            } else {
                txtNamaMobil.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNamaMobilKeyPressed

    private void txtNamaMobilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaMobilKeyTyped
        // TODO add your handling code here:
        if (txtNamaMobil.getText().length()>30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNamaMobilKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width-this.getWidth())/2;
        int y = (posisi.height-this.getHeight())/2;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbMobil;
    private javax.swing.JTextField txtIdMobil;
    private javax.swing.JTextField txtNamaMobil;
    // End of variables declaration//GEN-END:variables

    public void SimpanData() {
        if (txtIdMobil.getText().equals("") || txtNamaMobil.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informasi Harus Diisi Semua");
        } else {
            try {
                mob.AksesData();
                mob.id_mobil = txtIdMobil.getText();
                mob.nama_mobil = txtNamaMobil.getText();
                mob.Simpan();
                mob.res.executeUpdate(mob.sql);
                mob.conn.close();
                Bersih();
                isiTabel();
                
                JOptionPane.showMessageDialog(null, "Informasi Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
                System.out.println(e.getMessage());
            }
        }
    }

}
