/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualanmobil;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.table.*;

/**
 *
 * @author USER
 */
public class FormTipe extends javax.swing.JFrame {
    Tipe tip = new Tipe();
    private TableColumn column;

    /**
     * Creates new form FormTipe
     */
    public FormTipe() {
        initComponents();
        tip.AksesData();
        isiTabel();
    }
    
    public void isiTabel() {
        DefaultTableModel tm = new DefaultTableModel();
        
        tm.addColumn("ID Tipe");
        tm.addColumn("Nama Tipe");
        
        try {
            tip.AksesData();
            tip.TampilData();
            Statement stat = tip.conn.createStatement();
            ResultSet res = stat.executeQuery(tip.sql);
            while(res.next()) {
                tm.addRow(new Object[] {res.getString(1), res.getString(2)});
            }tbTipe.setModel(tm);
        } catch (Exception e) {
        }
    }
    
    public void Bersih(){
        txtIdTipe.setText("");
        txtNamaTipe.setText("");
        txtIdTipe.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdTipe = new javax.swing.JTextField();
        txtNamaTipe = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTipe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("FORM TIPE");

        jLabel2.setText("ID Tipe           :");

        jLabel3.setText("Nama Tipe    :");

        txtIdTipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdTipeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdTipeKeyTyped(evt);
            }
        });

        txtNamaTipe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaTipeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaTipeKeyTyped(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        tbTipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Tipe", "Nama Tipe"
            }
        ));
        tbTipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTipeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTipe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaTipe))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdTipe))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar)))
                .addGap(90, 145, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (txtIdTipe.getText().equals("") || txtNamaTipe.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Informasi Mobil");
        } else {
            try {
                tip.AksesData();
                tip.id_tipe = txtIdTipe.getText();
                tip.nama_tipe = txtNamaTipe.getText();
                tip.Edit();
                tip.res.executeUpdate(tip.sql);
                tip.conn.close();
                Bersih();
                isiTabel();
                
                JOptionPane.showMessageDialog(null, "Informasi Berhasil diUpdate");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menyimpan");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            tip.AksesData();
            tip.id_tipe = txtIdTipe.getText();
            tip.Hapus();
            tip.res.executeUpdate(tip.sql);
            tip.conn.close();
            isiTabel();
            Bersih();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tbTipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTipeMouseClicked
        // TODO add your handling code here:
        int baris = tbTipe.getSelectedRow();
        String kolom1 = tbTipe.getValueAt(baris, 0).toString();
        String kolom2 = tbTipe.getValueAt(baris, 1).toString();
        
        txtIdTipe.setText(kolom1);
        txtNamaTipe.setText(kolom2);
    }//GEN-LAST:event_tbTipeMouseClicked

    private void txtIdTipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdTipeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtIdTipe.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan ID Tipe", "informasi", JOptionPane.INFORMATION_MESSAGE);
                txtIdTipe.requestFocus();
            } else {
                txtIdTipe.requestFocus();
            }
        }
    }//GEN-LAST:event_txtIdTipeKeyPressed

    private void txtIdTipeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdTipeKeyTyped
        // TODO add your handling code here:
        if (txtIdTipe.getText().length()>4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdTipeKeyTyped

    private void txtNamaTipeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaTipeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtNamaTipe.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan Nama Tipe", "informasi", JOptionPane.INFORMATION_MESSAGE);
                txtNamaTipe.requestFocus();
            } else {
                txtNamaTipe.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNamaTipeKeyPressed

    private void txtNamaTipeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaTipeKeyTyped
        // TODO add your handling code here:
        if (txtNamaTipe.getText().length()>30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNamaTipeKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width-this.getWidth())/2;
        int y = (posisi.height-this.getHeight())/2;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTipe;
    private javax.swing.JTextField txtIdTipe;
    private javax.swing.JTextField txtNamaTipe;
    // End of variables declaration//GEN-END:variables

    public void SimpanData() {
        if (txtIdTipe.getText().equals("") || txtNamaTipe.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informasi Harus Diisi Semua");
        } else {
            try {
                tip.AksesData();
                tip.id_tipe = txtIdTipe.getText();
                tip.nama_tipe = txtNamaTipe.getText();
                tip.Simpan();
                tip.res.executeUpdate(tip.sql);
                tip.conn.close();
                Bersih();
                isiTabel();
                
                JOptionPane.showMessageDialog(null, "Informasi Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
                System.out.println(e.getMessage());
            }
        }
    }

}
